### PR TITLE
Extract from log

### PR DESCRIPTION
**Pull request by benlaurie**
And add a Makefile.

### CODE REVIEW

**Comment by benlaurie** [comment]
Wrong repo!

**Comment by Martin2112** [comment]
Are you sure it's the wrong repo? Looked like a trillian example to me!

Martin

**Comment by benlaurie** [comment]
Yes, it is - but still a WIP. You can look at https://github.com/benlaurie/trillian-examples/pulls for the current status (each PR builds on the previous one, at least so far).

**Comment by Martin2112** [comment]
Ah, OK. Carry on!

Martin

**Pull request closed without merging**
