### PR TITLE
Add scorecard badge to main README

### PR DESCRIPTION
**Pull request by mhutchinson**

### CODE REVIEW

**Comment by roger2hk** [comment]
It doesn't work as expected.

image

**Comment by mhutchinson** [comment]
> It doesn't work as expected.
> 
> image

Whoops, I filled in the links and confirmed they worked and then somehow reverted back to the placeholder versions. Fixed now.

**Comment by roger2hk** [comment]
https://github.com/google/trillian-examples/security/code-scanning/46 is still open after merging this PR.

**Comment by mhutchinson** [comment]
> [CII-Best-Practices](/google/trillian-examples/security/code-scanning/46) is still open after merging this PR.

There's a lot of info in the remediation section, but I think this is a different badge that one gets for filling out https://bestpractices.coreinfrastructure.org/en. Current priority is burning down the issues now in the code scanning in severity order, so we'll come to this one last.

**Pull request merged**
