### PR TITLE
Updated to go1.21 and go mod tidy

### PR DESCRIPTION
**Pull request by mhutchinson**

### CODE REVIEW

**Review by roger2hk — APPROVED** [review]

**Comment by AlCutter** [comment]
Do we need/want to update Go versions in presubmits/Docker files/GCB configs/etc. too ?

**Comment by mhutchinson** [comment]
Yeah there's probably some more files to be updated. I'll update the PR in the morning.

**Comment by mhutchinson** [comment]
@AlCutter PTAL

**Comment by AlCutter** [comment]
> @AlCutter PTAL

I think you'll need to update `golangci-lint` in the integration test Dockerfile too - looks like you need [v1.54.0](https://github.com/golangci/golangci-lint/releases/tag/v1.54.0) or above for `go1.21` support (latest `golangci-lint` is [v1.55.2](https://github.com/golangci/golangci-lint/releases/tag/v1.55.2) BTW).

**Pull request merged**
