### PR TITLE
Add Firmware Transparency to repo

### PR DESCRIPTION
**Pull request by AlCutter**

### CODE REVIEW

**Comment by AlCutter** [comment]
@googlebot I fixed it.

(Well, Yogesh did!)

**Comment by mhutchinson** [comment]
@googlebot I consent.

**Review by mhutchinson — APPROVED** [review]

**Review by yogeshbdeshpande — APPROVED** [review]
"@googlebot I consent"

**Review by yogeshbdeshpande — APPROVED** [review]
"@googlebot I consent"

**Review by yogeshbdeshpande — APPROVED** [review]
"@googlebot I consent"

**Review by yogeshbdeshpande — APPROVED** [review]
@googlebot I consent

**Review by yogeshbdeshpande — APPROVED** [review]
@googlebot I consent

**Review by yogeshbdeshpande — APPROVED** [review]
@googlebot I consent

**Review by yogeshbdeshpande — APPROVED** [review]
@googlebot I consent

**Comment by AlCutter** [comment]
Corp SLA in place, and Yogesh has confirmed above that merging his commits is done with consent.

**Pull request merged**
