### PR TITLE
Bump go version to 1.22.8, tamago to 1.23.2 and sumdbverify base image to 1.22.8-alpine3.20

### PR DESCRIPTION
**Pull request by roger2hk**
This PR should unblock https://github.com/google/trillian-examples/pull/1256.

Go version bumps from 1.22.6 to 1.22.8.
tamago version bumps from 1.22.6 to 1.23.2.
clone/cmd/sumdbverify/Dockerfile base image bumps from 1.22.6-alpine3.20 to [1.22.8-alpine3.20](https://hub.docker.com/layers/library/golang/1.22.8-alpine3.20/images/sha256-e3bffcbc5c810bdd319f5354e49f2fb236c3c04a555b9d9b39a495c8b3d60249)

### CODE REVIEW

**Comment by mhutchinson** [comment]
You'll need to bump the version of tamago it seems

**Comment by roger2hk** [comment]
> You'll need to bump the version of tamago it seems

Ah, right. The latest version of tamago is 1.22.6. Let me ask Andrea if there will be a 1.22.8 version as [only 1.23.2 was released last month](https://github.com/usbarmory/tamago-go/releases/).

**Comment by mhutchinson** [comment]
Can we just bump this repo to 1.23.2 ?

**Comment by roger2hk** [comment]
Yeah, that should work. I think we want to maintain the N-1 version if possible.

**Comment by mhutchinson** [comment]
We don't need to be too precious about Trillian Examples as nobody should be depending on this for production code.

**Comment by roger2hk** [comment]
> We don't need to be too precious about Trillian Examples as nobody should be depending on this for production code.

Gotcha, that makes sense to me. Bumped tamago to 1.23.2.

**Pull request merged**
